name: build
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tacoss/nodejs@master
        with:
          args: make test BROWSER=chromium:headless
